# Generated by Django 5.0.7 on 2024-08-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='account_number',
            field=models.CharField(max_length=15),
        ),
    ]
